name: anti_jamf
description: A Flutter application to detect and mitigate jamf

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^11.3.0
  url_launcher: ^6.1.14     # Specify exact version
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
